const types = {
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	EDIT_TODO: 'EDIT_TODO',
	TOGGLE_COMPLETE_TODO: 'TOGGLE_COMPLETE_TODO',
	TOGGLE_EDITING_TODO: 'TOGGLE_EDITING_TODO',
	COMPLETE_ALL: 'COMPLETE_ALL',
	CLEAR_COMPLETED: 'CLEAR_COMPLETED',
};